[project]
name = "dbt-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-duckdb>=1.10.1",
    "dbt-core>=1.11.6",
    "duckdb>=1.4.4",
]
